"""Shared DataFlow LLM environment names and defaults."""

ENV_DF_API_BASE_URL = "DF_API_BASE_URL"
ENV_DF_API_URL = "DF_API_URL"
ENV_DF_MODEL_NAME = "DF_MODEL_NAME"
ENV_DF_API_KEY = "DF_API_KEY"

ENV_LLM_BASE_URL = "LLM_BASE_URL"
ENV_LLM_MODEL = "LLM_MODEL"

DEFAULT_DATAFLOW_API_BASE_URL = "https://api.openai.com/v1"
DEFAULT_DATAFLOW_API_URL = f"{DEFAULT_DATAFLOW_API_BASE_URL}/chat/completions"
DEFAULT_DATAFLOW_MODEL_NAME = "openai/gpt-5.6-luna"
